/**
 * Outputs for aws:executeAutomation
 */
export interface ExecuteAutomationOutputs {
    /**
     * The ID of the secondary automation.
     */
    readonly executionId: string;
  
    /**
     * The status of the secondary automation.
     */
    readonly status: string;
  
    /**
     * The output generated by the secondary automation.
     */
    readonly output?: Record<string, string[]>;
}
  
/**
 * Inputs for aws:executeAutomation
 */
export interface ExecuteAutomationProps {
    /*
     * The name of the secondary runbook to run during the step. For runbooks in the same AWS account, specify the runbook name. For runbooks shared from a different AWS account, specify the Amazon Resource Name (ARN) of the runbook. For information about using shared runbooks, see Using shared SSM documents.
     */
    readonly documentName: string;

    /*
     * The version of the secondary runbook to run. If not specified, Automation runs the default runbook version.
     */
    readonly documentVersion?: string;

    /*
     * The maximum number of targets allowed to run this task in parallel. You can specify a number, such as 10, or a percentage, such as 10%.
     */
    readonly maxConcurrency?: string;

    /*
     * The number of errors that are allowed before the system stops running the automation on additional targets. You can specify either an absolute number of errors, for example 10, or a percentage of the target set, for example 10%. If you specify 3, for example, the system stops running the automation when the fourth error is received. If you specify 0, then the system stops running the automation on additional targets after the first error result is returned. If you run an automation on 50 resources and set MaxErrors to 10%, then the system stops running the automation on additional targets when the sixth error is received.
     */
    readonly maxErrors?: string;

    /*
     * Required parameters for the secondary runbook. The mapping uses the following format: {"parameter1" : "value1", "parameter2" : "value2" }
     */
    readonly runtimeParameters?: Record<string, any>;

    /*
     * Optional metadata that you assign to a resource. You can specify a maximum of five tags for an automation.
     */
    readonly tags?: Record<string, any>[];

    /*
     * A location is a combination of AWS Regions and/or AWS accounts where you want to run the automation. A minimum number of 1 item must be specified and a maximum number of 100 items can be specified.
     */
    readonly targetLocations?: Record<string, any>[];

    /*
    * A list of key-value mappings of document parameters to target resources. Both Targets and TargetMaps can't be specified together.
    */
    readonly targetMaps?: Record<string, any>[];

    /*
    * The name of the parameter used as the target resource for the rate-controlled automation. Required if you specify Targets.
    */
    readonly targetParameterName?: string;

    /*
    * A list of key-value mappings to target resources. Required if you specify TargetParameterName.
    */
    readonly targets?: Record<string, any>[];
  }
  
  /**
   * Interface for simulating aws:executeAutomation
   */
  export interface IExecuteAutomationHook {
    /**
       * Simulate the aws:executeAutomation
       */
    execute(props: ExecuteAutomationProps): ExecuteAutomationOutputs;
  }
  
  export * from './execute-automation-hook/api-execute-automation-hook';